name: tawseel
description: find best delivery price
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.4+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.7
  auto_route: ^5.0.2
  cached_network_image: ^3.2.2
  collection: ^1.16.0
  connectivity_plus: ^2.3.7
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  dotted_border: ^2.0.0+3
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.1+1
  equatable: ^2.0.5
  external_app_launcher: ^3.1.0
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_native_image: ^0.0.6+1
  flutter_svg: ^1.1.6
  flutter_toggle_tab: ^1.2.0
  focused_menu: ^1.0.5
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.1
  image_picker: ^0.8.6
  infinite_scroll_pagination: ^3.2.0
  json_annotation: ^4.7.0
  location: ^4.4.0
  logger: any
  material_floating_search_bar: ^0.3.7
  meta: ^1.8.0
  modal_bottom_sheet: ^2.1.2
  pin_code_fields: ^7.4.0
  provider: ^6.0.4
  pull_to_refresh: ^2.0.0
  retrofit: ^3.3.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  carousel_slider: ^4.1.1
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_analytics: ^10.0.6
  firebase_messaging: ^14.1.2
  device_apps: ^2.2.0

dev_dependencies:
  build_runner: any
  auto_route_generator: ^5.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0

  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  flutter_native_splash: ^2.2.15

flutter_native_splash:
  background_image: assets/splash_background.png

dependency_overrides:
  platform: ^3.1.0

flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/langs/
    - assets/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 200
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 300
        - asset: assets/fonts/Almarai-SemiBold.ttf
          weight: 500
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
