/// Generated by AssetsRefGenerator on 2021/08/31
class Res {
  static const String apple_icon = "assets/apple-icon.png";
  static const String apple_icon_svg = "assets/apple-white.svg";

  static const String fullname_icon = "assets/fullname-icon.png";
  static const String google_icon = "assets/google-icon.png";
  static const String intro_image = "assets/intro-image.png";
  static const String logo_splash = "assets/logo-splash.png";
  static const String password_icon = "assets/password-icon.png";
  static const String password_visability = "assets/password-visability.png";
  static const String phone_icon = "assets/phone-icon.png";
  static const String back_icon = "assets/back.svg";
  static const String location_icon = "assets/location_icon.png";

  static const String home_icon = "assets/home-icon.png";
  static const String offers_icon = "assets/home-offers.png";
  static const String fav_icon = "assets/home-favorites.png";
  static const String profile_icon = "assets/home-profile.png";

  static const String email_icon = "assets/email_icon.png";
  static const String pick_image_icon = "assets/pick_image_icon.png";
  static const String pick_image_camera_icon = "assets/camera-icon.png";
}
