/// Generated by AssetsRefGenerator on 2021/08/31
class Res {
  static const String apple_icon = "assets/apple-icon.png";
  static const String apple_icon_svg = "assets/apple-white.svg";

  static const String fullname_icon = "assets/fullname-icon.png";
  static const String google_icon = "assets/google-icon.png";
  static const String intro_image = "assets/intro-image.png";
  static const String logo_splash = "assets/logo-splash.png";
  static const String password_icon = "assets/password-icon.png";
  static const String password_visability = "assets/password-visability.png";
  static const String phone_icon = "assets/phone-icon.png";
  static const String back_icon = "assets/back.svg";
  static const String location_icon = "assets/location_icon.png";
  static const String home_location_icon = "assets/home-location-icon.png";

  static const String home_icon = "assets/home-icon.png";
  static const String offers_icon = "assets/home-offers.png";
  static const String fav_icon = "assets/home-favorites.png";
  static const String profile_icon = "assets/home-profile.png";

  static const String email_icon = "assets/email_icon.png";
  static const String pick_image_icon = "assets/pick_image_icon.png";
  static const String pick_image_camera_icon = "assets/camera-icon.png";

  static const String password_changed_image =
      "assets/password-changed-image.png";

  static const String about_us_icon = "assets/about-us-icon.png";
  static const String change_phone_icon = "assets/change-phone-icon.png";
  static const String address_icon = "assets/address-icon.png";
  static const String edit_icon = "assets/edit-icon.png";
  static const String language_icon = "assets/language-icon.png";
  static const String lock_icon = "assets/lock-icon.png";
  static const String logout_icon = "assets/logout-icon.png";
  static const String notification_icon = "assets/notification-icon.png";
  static const String support_icon = "assets/support-icon.png";
  static const String terms_icon = "assets/terms-icon.png";
  static const String map_pic = "assets/map-pic.png";
  static const String three_dots = "assets/three-dots.png";

  static const String settings_icon = "assets/settings-icon.png";
  static const String search_icon = "assets/search-icon.png";
  static const String category_icon = "assets/cat-icon.png";
  static const String star_icon = "assets/star.png";
  static const String watch_icon = "assets/watch-icon.png";
  static const String heart_icon = "assets/heart-icon.png";
  static const String delete_icon = "assets/delete.png";
  static const String no_favorites_image = "assets/no_favorites.png";
}
